-- AlterTable
ALTER TABLE "games" ADD COLUMN     "opp_ot" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "opp_q1" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "opp_q2" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "opp_q3" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "opp_q4" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "team_ot" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "team_q1" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "team_q2" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "team_q3" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "team_q4" INTEGER NOT NULL DEFAULT 0;
