-- CreateEnum
CREATE TYPE "play_type" AS ENUM ('SCRIMMAGE', 'TOUCHDOWN', 'EXTRA_POINT', 'EXTRA_POINT_MISSED', 'TWO_POINT', 'TWO_POINT_FAILED', 'FIELD_GOAL', 'FIELD_GOAL_MISSED', 'SAFETY', 'PUNT', 'INTERCEPTION', 'FUMBLE', 'TURNOVER_ON_DOWNS', 'KICKOFF', 'PENALTY', 'KNEEL', 'END_PERIOD', 'OTHER');

-- AlterTable
ALTER TABLE "game_plays" ADD COLUMN     "play_type" "play_type" NOT NULL DEFAULT 'SCRIMMAGE',
ADD COLUMN     "points" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "scoring_team" "scoring_team";
