---
title: "Important Players for the 2026/2027 Season"
---

# QB Bryce Joiner

Bryce Joiner is a redshirt freshman who boasts a ton of talent. Having sat on the bench at Grambling State for most of last year, Caddo State picked him up in a steal after watching him perform after the Grambling starter was injured late in the year. Joiner boasts a strong throwing arm and tremendous running ability. 

# RB AJ Trimble 

Trimble is a  red shirt sophmore returning to Caddo State for his 3rd year. Having been with the team since the jump to the FCS he has seen a lot of action and represents the most mature runnnig back in the running room for Caddo State. Expect him to operate in a captaincy role and to share carries with the other important player J.J. Carden.

# RB JJ Carden

Carden is a Junior transfer from Louisville where he saw playing time in 76 carries for 212 yards and 2 TD last year. Unhappy with his playing time he decided to take a chance and jump ship for FBS newcomer Caddo State. Carden was a four star recruit coming out of highschool and will expect significant playing time. Expect the fact that he will have to share carries with AJ Trimble to be a sticking point.

# WR Kareem Eber

The junior wideout Kareem Eber represents the most obvious WR1 for Caddo State in the upcoming year. He is 6'3" 202lbs and is excellent at the point of catch. The junior sat out most of the 2025-26 FCS playoff run with an injured shoulder but returns to the starting lineup looking for vengence as the team join the FBS.

# WR Deyonte Hocker III

True freshman Deyonte Hocker III is a high school trackstar turned college football wideout, he was a Texas All-State 100m and 200m runner and won gold in 5A 200m in his senior year. He joins Caddo State hoping to make a name for himself in College football after few D1 recruiting oppurtunities came his way. 

# LEDGE James Anenih

The Junior edge transferred in from SDSU after playing against Caddo State in the FCS playoff quarter finals last year. He wanted to make the jump to the FBS level and Caddo State's coaching staff were impressed with his rushing ability after he put up 3 sacks against Caddo State in a close win for Caddo in the FCS quarterfinals. When coaches reached out over the summer to see if Anenih was interested in joining them in the jump to FBS he didn't hesitate. 

# CB Kione Bryant

The Redshirt sophmore transferred in from UMass over the summer, having sat on the bench for his first two years and watching UMass perform poorly, he's looking for a new oppurtunity to make a name for himself by transferring to Caddo State, Kione Bryant's film impresses but he has very little experience actually playing. 

